version: "3"

services:
  web:
    image: nginx
    networks:
      net2:
        ipv4_address: 10.12.112.5
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - jenkins

  jenkins:
    image: jenkins/jenkins:lts
    networks:
      net2:
        ipv4_address: 10.12.112.6
    environment:
      - JAVA_OPTS=
        -Djenkins.install.runSetupWizard=false
        -Djava.awt.headless=true
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - JENKINS_OPTS="--prefix=/jenkins"
      - PLUGINS=
        workflow-aggregator
        job-dsl
        maven-plugin
        pipeline-maven
        matrix-auth
        antisamy-markup-formatter
        docker-plugin
        greenballs
        ansicolor
        git
        nexusArtifactUploader
    ports:
      - 8080:8080
    volumes:
      - jenkins_data:/var/jenkins_home
    entrypoint: /bin/bash
    command:
      - -c
      - |-
          /usr/local/bin/install-plugins.sh $${PLUGINS}
          /sbin/tini -- /usr/local/bin/jenkins.sh


  nexus:
    image: sonatype/nexus3
    environment:
      NEXUS_CONTEXT: nexus
    networks:
      net2:
        ipv4_address: 10.12.112.10
    ports:
      - 8081:8081
    volumes:
      - nexus_data:/nexus-data


volumes:
  jenkins_data:
  nexus_data:

networks:
  net2:
    ipam:
      driver: default
      config:
         - subnet: 10.12.112.0/22


