version: "3"

services:
  web:
    image: nginx
    logging:
      driver: journald
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - jenkins   

  jenkins:
    image: jenkins/jenkins:lts
    logging:
      driver: journald
    environment:
      - JAVA_OPTS=
        -Djenkins.install.runSetupWizard=false
        -Djava.awt.headless=true
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - PLUGINS=
        workflow-aggregator
        job-dsl
        maven-plugin
        pipeline-maven
        matrix-auth
        antisamy-markup-formatter
        docker-plugin
        greenballs
        ansicolor
        git  
    ports:
      - 8080:8080
    volumes:
      - jenkins_data:/var/jenkins_home
    entrypoint: /bin/bash
    command:
      - -c
      - |-
          /usr/local/bin/install-plugins.sh $${PLUGINS}
          /sbin/tini -- /usr/local/bin/jenkins.sh
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M

  nexus:
    image: sonatype/nexus3
    logging:
      driver: journald
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 500M

volumes:
  jenkins_data:
  nexus_data:
networks:
  net1:


